[package]
name = "scip-sys"
version = "0.1.3"
edition = "2021"
description = "Bindings for the C SCIP solver."
license = "Apache-2.0"
links = "scip"

[dependencies]

[build-dependencies]
bindgen = "0.64"
cc = "1.0.73"
glob = "0.3.1"